apiVersion: v1
kind: ServiceAccount
metadata:
  name:   fortio-server-medium
---
apiVersion: v1
kind: Service
metadata:
  name:   fortio-server-medium
spec:
  selector:
    app:   fortio-server-medium
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 8079
    targetPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:   fortio-server-medium
  name:   fortio-server-medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   fortio-server-medium
  template:
    metadata:
      annotations:
      labels:
        app:   fortio-server-medium
    spec:
      containers:
      - name:   fortio-server-medium
        image: fortio/fortio:latest_release
        env:       
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping        
      serviceAccountName:   fortio-server-medium
      nodeSelector:
        nodetype: services