apiVersion: v1
kind: ServiceAccount
metadata:
  name:   fortio-server-small
---
apiVersion: v1
kind: Service
metadata:
  name:   fortio-server-small
spec:
  selector:
    app:   fortio-server-small
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 8079
    targetPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:   fortio-server-small
  name:   fortio-server-small
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   fortio-server-small
  template:
    metadata:
      annotations:
      labels:
        app:   fortio-server-small
    spec:
      containers:
      - name:   fortio-server-small
        image: fortio/fortio:latest_release
        env:       
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping        
      serviceAccountName:   fortio-server-small
      nodeSelector:
        nodetype: services