{
 "title": "Kubernetes / Views / Consul / ServiceMesh",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,exported_namespace)"
    }
   },
   { "name": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "Mem Usage % by pod limits",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max (container_memory_working_set_bytes{namespace=\"$namespace\"} / on(container, pod) label_replace(kube_pod_container_resource_limits{resource=\"memory\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\")) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %  by pod limits",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])\n    / on (container, pod)\n  label_replace(kube_pod_container_resource_limits{resource=\"cpu\"}, \"pod\", \"$1\", \"exported_pod\", \"(.+)\")\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", container=\"consul-dataplane\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Dataplane Latency ( $app )",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\", app=~\"$app\"}[5m])))\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\", app=~\"$app\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\", app=~\"$app\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(.999, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\", app=~\"$app\"}[5m])))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "P50 Latency by App",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le,app) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P75 Latency by App",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le,app) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Latency by App",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le,app) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Latency by App",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, app) (rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Throughput by Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",envoy_cluster_name!~\"prometheus_backend|local_app\"}[5m])) - on() sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"1\",envoy_cluster_name!~\"prometheus_backend|local_app\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "<1ms"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",envoy_cluster_name!~\"prometheus_backend|local_app\"}[5m])) - on() sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"5\",envoy_cluster_name!~\"prometheus_backend|local_app\",namespace=\"$namespace\"}[5m]))\n",
     "legendFormat": "<5ms"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",envoy_cluster_name!~\"prometheus_backend|local_app\"}[5m])) - on() sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"10\",envoy_cluster_name!~\"prometheus_backend|local_app\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "<10ms"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",envoy_cluster_name!~\"prometheus_backend|local_app\"}[5m])) - on() sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"25\",envoy_cluster_name!~\"prometheus_backend|local_app\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "<25ms"
    }
   ]
  },
  {
   "title": "HTTP Status Codes ( $app )",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum by(app, envoy_response_code_class) (increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"public_listener\", namespace=\"$namespace\", app=~\"$app\"}[5m]))",
     "legendFormat": "{{app}}-{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "GRPC Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (app)(rate(envoy_listener_http_fortio_server_defaults_grpc_fortio_consul_default_dc1_downstream_rq_xx{envoy_response_code_class=~\"1|3|4|5\"}[$__rate_interval]))",
     "legendFormat": "{{app}}-errors"
    },
    {
     "expr": "rate(envoy_listener_http_fortio_server_defaults_grpc_fortio_consul_default_dc1_downstream_rq_xx{envoy_response_code_class=\"2\"}[$__rate_interval])",
     "legendFormat": "{{app}}-success"
    }
   ]
  },
  {
   "title": "Network Bytes Rx and Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$app.*\"}[5m])",
     "legendFormat": "{{pod}}-rx"
    },
    {
     "expr": "- rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$app.*\"}[5m])",
     "legendFormat": "{{pod}}-tx"
    },
    {
     "expr": "sum(rate(node_network_receive_drop_total{component=\"node-exporter\"}[5m]))",
     "legendFormat": "global-dropped-pkts"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Envoy Config Stale",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "group(envoy_control_plane_connected_state{namespace=\"$namespace\"}) by (local_cluster)",
       "legendFormat": "{{local_cluster}}"
      }
     ]
    },
    {
     "title": "Downstream Rq Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(increase(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (app)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upstream Rq Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by(app)(increase(envoy_cluster_upstream_rq_total[5m]))",
       "legendFormat": "{{consul_destination_service}}"
      }
     ]
    },
    {
     "title": "Downstream Rq by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"public_listener\"}[5m])) by (app,envoy_response_code_class)\n",
       "legendFormat": "{{app}}-{{envoy_response_code_class}}xx"
      }
     ]
    },
    {
     "title": "Upstream Rq by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by(app,envoy_response_code_class) (increase(envoy_cluster_upstream_rq_xx[5m]))",
       "legendFormat": "{{app}}-{{envoy_response_code_class}}xx"
      }
     ]
    }
   ]
  }
 ]
}