apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
        'consul.hashicorp.com/enable-metrics': 'true'
        'consul.hashicorp.com/enable-metrics-merging': 'true'
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nicholasjackson/fake-service:v0.24.2
        env:
        # - name: UPSTREAM_URIS
        #   value: http://api.default.svc.cluster.local:9090
        - name: NAME
          value: Frontend (with metrics, he hopes)
        ports:
        - containerPort: 9090
      serviceAccountName: frontend
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
spec:
  destination:
    name: frontend
  sources:
    - name: ingress-gateway
      action: allow
    - name: fortio-client
      action: allow