apiVersion: v1
kind: ServiceAccount
metadata:
  name:   fortio-server-defaults
  namespace: fortio-consul-150-router
---
apiVersion: v1
kind: Service
metadata:
  name:   fortio-server-defaults
  namespace: fortio-consul-150-router
spec:
  selector:
    app:   fortio-server-defaults
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fortio-consul-150-router
  labels:
    app:   fortio-server-defaults
  name:   fortio-server-defaults
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   fortio-server-defaults
  template:
    metadata:
      namespace: fortio-consul-150-router
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
        'consul.hashicorp.com/sidecar-proxy-cpu-limit': '150m' # 35% of a CPU
        'consul.hashicorp.com/sidecar-proxy-cpu-request': '150m'
        'consul.hashicorp.com/sidecar-proxy-memory-limit': '100Mi'
        'consul.hashicorp.com/sidecar-proxy-memory-request': '100Mi'
      labels:
        app:   fortio-server-defaults
    spec:
      containers:
      - name:   fortio-server-defaults
        image: fortio/fortio:latest_release
        env:       
        ports:
        - containerPort: 8080
          name: http-fortio
      serviceAccountName:   fortio-server-defaults
      nodeSelector:
        nodegroup: services