apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: fortio-client
  namespace: fortio-consul-100
spec:
  destination:
    name: fortio-client
  sources:
    - name: ingress-gateway
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name:   fortio-server-defaults
  namespace: fortio-consul-100
spec:
  destination:
    name:   fortio-server-defaults
  sources:
    - name: fortio-client
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name:   fortio-server-defaults-grpc
  namespace: fortio-consul-100
spec:
  destination:
    name:   fortio-server-defaults-grpc
  sources:
    - name: fortio-client
      action: allow
