adminPassword: password

rbac:
  create: false
  pspEnabled: false

# Disable test pods
testFramework:
  enabled: false

podLabels:
  app: grafana

podAnnotations:
  "consul.hashicorp.com/connect-inject": "false"

service:
  enabled: true
  type: LoadBalancer
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  port: 3000
  targetPort: 3000

# Configure the prometheus data source. We expect prometheus:9090 in the same namespace.
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        orgId: 1
        url: http://prometheus-server.metrics.svc.cluster.local
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 5s
        editable: true
dashboards:
  default:
    local-dashboard:
      url: https://https://raw.githubusercontent.com/ppresto/terraform-aws-azure-load-test/patrick/deploy/grafana/k8s-views-consul-mesh.json